### ISSUE TITLE
Fatal error after upgrade to Prestashop 1.7.7.0

### ISSUE THREAD

**Issue by Frankyet** [SIELOnline/Acumulus-for-PrestaShop#2]
After upgrade to 1.7.7.0 and go to modules
fatal error see print sreen.

Acumulus latest version.
![image](https://user-images.githubusercontent.com/22242384/101214221-f0936180-367b-11eb-89c8-b514cd47b4da.png)

**Comment by fietserwin** [comment]
I'm currently working on a new version that will include several new features and that will be tested on 1.7.7.x. But to also test it on 1.7.6 I wanted to do the upgrade an testing of 1.7.7 as last part of creating that new release.

Apparently PS introduced a new property in their class Module with the same name as a property that I already use in my Acumulus class. Please rename that property (on lines 43, 72, and 134) to confirmUninstallMsg and you should be able to continue.
