### ISSUE TITLE
Module not installable

### ISSUE THREAD

**Issue by AaronTajriba** [SIELOnline/Acumulus-for-PrestaShop#3]
PS 1.7.8.7
PHP 7.4

When trying an install i get the following error:

![Schermafbeelding 2022-10-03 om 15 34 31](https://user-images.githubusercontent.com/70962249/193590820-87b78fe4-c406-4e52-9b3d-041a0b6ca27d.png)

When going to the lib/siel folder i found this is empty. There is only an quicklink to "D:/Projecten/Acumulus/libAcumulusTest/libAcumulus"

The module is not installable

**Comment by fietserwin** [comment]
Install from https://forum.acumulus.nl/index.php/topic,2745.0.html.

- PS does not allow free modules on their market place (no margin for them).
- PS does not  use composer when installing modules
- This github project is the PS part only and the generic library is in another github project, they are bundled in the above specified download.
